[window]
padding = { x = 8, y = 8 }
decorations = "full"
dynamic_title = true
opacity = 0.6

[cursor.style]
shape = "Beam"
blinking = "Never"

[font]
size = 11
normal = { family = "JetBrainsMonoNerdFont", style = "SemiBold" }

[colors.primary]
background = "#000000"
foreground = "#cdd6f4"

[colors.normal]
black   = "#45475a"
red     = "#f38ba8"
green   = "#a6e3a1"
yellow  = "#f9e2af"
blue    = "#89b4fa"
magenta = "#f5c2e7"
cyan    = "#94e2d5"
white   = "#bac2de"

[colors.bright]
black   = "#585b70"
red     = "#f38ba8"
green   = "#a6e3a1"
yellow  = "#f9e2af"
blue    = "#89b4fa"
magenta = "#f5c2e7"
cyan    = "#94e2d5"
white   = "#a6adc8"
